my_list=[8, 10, 6, 2, 4]
my_list.sort()
print(my_list)

lst = ["D", "F", "A", "Z"]
lst.sort()

print(lst)

# The sort() method sorts the elements of a given list in a specific order - Ascending or Descending. The default order is ascending, but you can pass the reverse=True argument to sort in descending order. Lists are mutable, so we can change the order of their elements. The sort() method takes an optional argument reverse=True, which will sort the list in descending order. The sort() method modifies the original list and returns None. The sorted() function returns a new sorted list from the elements of any iterable. The sorted() function does not modify the original list. The sorted() function returns a new sorted list from the elements of any iterable. The sorted() function does not modify the original list. The sort() method sorts the elements of a given list in a specific order - Ascending or Descending. The default order is ascending, but you can pass the reverse=True argument to sort in descending order. Lists are mutable, so we can change the order of their elements. The sort() method takes an optional argument reverse=True, which will sort the list in descending order. The sort() method modifies the original list and returns None. The sorted() function returns a new sorted list from the elements of any iterable. The sorted() function does not modify the original list. The sorted() function returns a new sorted list from the elements of any iterable. The sorted() function does not modify the original list. The sort() method sorts the elements of a given list in a specific order - Ascending or Descending. The default order is ascending, but you can pass the reverse=True argument to sort in descending order. Lists are mutable, so we can change the order of their elements. The sort() method takes an optional argument reverse=True, which will sort the list in descending order. The sort() method modifies the original list and returns None. The sorted() function returns a new sorted list from the elements of any iterable. The sorted() function does not modify the original list. The sorted() function returns a new sorted list from the elements of any iterable. The sorted() function does not modify the original list. The sort() method sorts the elements of a given list in a specific order - Ascending or Descending. The default order is ascending, but you can pass the reverse=True argument to sort in descending order. Lists are mutable, so we can change the order of their elements. The sort() method takes an optional argument reverse=True, which will sort the list